### ISSUE TITLE
Constant refresh of widget

### ISSUE THREAD

**Issue by as703** [pittica/gatsby-plugin-trustpilot-widget#2]
Many thanks for this widget. I use it on my site here: [www.c19testing.co.uk/foryou](https://www.c19testing.co.uk/foryou).

I have it in a header component at the top of the page and then in the main body of te page as well. However, I've found that if the page is refreshed once then the the instance of the widget in the header at the top of the page continually reloads / refreshes. You can see this behavious if you vistit link included above nad refresh the page.

If I remove the second instance of the widget - half way down the page - this behavious stops and the header widget works as expected. For example in all the other pages on the site that don't have the second instance of the widget refreshing has no effect.

I'd be very grateful for any insight you might have into why having two instances of the widget on a page appears to cause issues.

Many thanks.

**Comment by aditya2048** [comment]
Getting the same issue also not able to determine why is this happening.

**Comment by luciobenini** [comment]
Maybe solved updating to React 17
